/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    copy: typeof import('./components/DemoEc copy.vue')['default']
    DemoEc: typeof import('./components/DemoEc.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    ProductCard: typeof import('./components/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
